//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class alums_asigs
    {
        public int id_alumno { get; set; }
        public int id_asignatura { get; set; }
        public float nota { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual asignatura asignatura { get; set; }
    }
}
